### ISSUE TITLE
Better than `iconsax` on pub.dev?

### ISSUE THREAD

**Issue by MoyinShabi** [PersianFlutter/iconsax_flutter#1]
Hi @payam-zahedi, I'd like to ask, please: would you recommend that I use your newly created `iconsax_flutter` package instead of the previously existing `iconsax` package on pub.dev, and why please?

Thank you in advance for your response!

**Comment by payam-zahedi** [comment]
Hey @MoyinShabi 
The reason is `iconax_flutter` has an issue on web. basicly You can not use it on web projects.

Check out this [issue](https://github.com/luisDanielRoviraContreras/flutter_iconsax/issues/6).
